"""init_all_tables

Revision ID: 0c004db19d3b
Revises: 
Create Date: 2025-04-05 22:54:28.543811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c004db19d3b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('userName', sa.String(length=100), nullable=True),
    sa.Column('firstName', sa.String(length=100), nullable=True),
    sa.Column('lastName', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('token', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_firstName'), 'users', ['firstName'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_lastName'), 'users', ['lastName'], unique=False)
    op.create_index(op.f('ix_users_password'), 'users', ['password'], unique=False)
    op.create_index(op.f('ix_users_userName'), 'users', ['userName'], unique=False)
    op.create_table('discussions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('d_Name', sa.String(length=100), nullable=True),
    sa.Column('d_Profile', sa.String(length=255), nullable=True),
    sa.Column('d_Description', sa.String(length=255), nullable=True),
    sa.Column('OwnerId', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['OwnerId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discussions_OwnerId'), 'discussions', ['OwnerId'], unique=False)
    op.create_index(op.f('ix_discussions_d_Description'), 'discussions', ['d_Description'], unique=False)
    op.create_index(op.f('ix_discussions_d_Name'), 'discussions', ['d_Name'], unique=False)
    op.create_index(op.f('ix_discussions_d_Profile'), 'discussions', ['d_Profile'], unique=False)
    op.create_index(op.f('ix_discussions_id'), 'discussions', ['id'], unique=False)
    op.create_table('joinings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.String(length=100), nullable=True),
    sa.Column('discussionId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['discussionId'], ['discussions.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_joinings_discussionId'), 'joinings', ['discussionId'], unique=False)
    op.create_index(op.f('ix_joinings_id'), 'joinings', ['id'], unique=False)
    op.create_index(op.f('ix_joinings_userId'), 'joinings', ['userId'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('postedBy', sa.String(length=100), nullable=True),
    sa.Column('questionId', sa.Integer(), nullable=True),
    sa.Column('discussionId', sa.Integer(), nullable=True),
    sa.Column('postType', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['discussionId'], ['discussions.id'], ),
    sa.ForeignKeyConstraint(['postedBy'], ['users.id'], ),
    sa.ForeignKeyConstraint(['questionId'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
    op.create_index(op.f('ix_posts_postType'), 'posts', ['postType'], unique=False)
    op.create_index(op.f('ix_posts_postedBy'), 'posts', ['postedBy'], unique=False)
    op.create_index(op.f('ix_posts_title'), 'posts', ['title'], unique=False)
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.String(length=255), nullable=True),
    sa.Column('postId', sa.Integer(), nullable=True),
    sa.Column('voteType', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['postId'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_votes_id'), 'votes', ['id'], unique=False)
    op.create_index(op.f('ix_votes_postId'), 'votes', ['postId'], unique=False)
    op.create_index(op.f('ix_votes_userId'), 'votes', ['userId'], unique=False)
    op.create_index(op.f('ix_votes_voteType'), 'votes', ['voteType'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_votes_voteType'), table_name='votes')
    op.drop_index(op.f('ix_votes_userId'), table_name='votes')
    op.drop_index(op.f('ix_votes_postId'), table_name='votes')
    op.drop_index(op.f('ix_votes_id'), table_name='votes')
    op.drop_table('votes')
    op.drop_index(op.f('ix_posts_title'), table_name='posts')
    op.drop_index(op.f('ix_posts_postedBy'), table_name='posts')
    op.drop_index(op.f('ix_posts_postType'), table_name='posts')
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_joinings_userId'), table_name='joinings')
    op.drop_index(op.f('ix_joinings_id'), table_name='joinings')
    op.drop_index(op.f('ix_joinings_discussionId'), table_name='joinings')
    op.drop_table('joinings')
    op.drop_index(op.f('ix_discussions_id'), table_name='discussions')
    op.drop_index(op.f('ix_discussions_d_Profile'), table_name='discussions')
    op.drop_index(op.f('ix_discussions_d_Name'), table_name='discussions')
    op.drop_index(op.f('ix_discussions_d_Description'), table_name='discussions')
    op.drop_index(op.f('ix_discussions_OwnerId'), table_name='discussions')
    op.drop_table('discussions')
    op.drop_index(op.f('ix_users_userName'), table_name='users')
    op.drop_index(op.f('ix_users_password'), table_name='users')
    op.drop_index(op.f('ix_users_lastName'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_firstName'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
